/**
 * Seed-data filter for public list endpoints.
 *
 * Staging/dev DBs accumulate test rows via smoke tests, mosaic critique
 * runs, and manual QA (titles like "TEST notify", "fыафыа", "asg",
 * emails like "smoke+...@metromap.test", "mosaic+...@metromap.test").
 * Those rows must NOT leak onto user-facing surfaces (public requests
 * feed, "Мои заявки", thread/message previews, public profiles).
 *
 * The filter is enabled by default and can be disabled per environment
 * via `ALLOW_SEED_DATA=1` (e.g. for local dev when you actually want
 * to see seed data while iterating). It is always enabled in
 * production regardless of the flag.
 */
import { Prisma } from "@prisma/client";
import { config } from "./config";

const ALLOW_SEED_DATA =
  !config.isProd && process.env.ALLOW_SEED_DATA === "1";

/** Email patterns generated by automated test infra. */
const TEST_EMAIL_PATTERNS = [
  "@metromap.test",
  "@example.test",
  "@p2ptax.test",
];

/** Title/body patterns for QA garbage strings. */
const TEST_TITLE_PATTERNS = [
  "TEST notify",
  "smoke test",
  "E2E test",
  "fыафыа",
  "фыафыа",
  // Short ascii keymashes used by manual QA. We keep this list tight
  // so we never hide a legitimately-short user title.
];

/** Exact-match short keymash titles (case-insensitive). */
const TEST_TITLE_EXACT = ["asg", "asgsdfg", "asdf", "qwer", "test123", "test"];

/**
 * Returns a Prisma `where` clause fragment that excludes test/seed
 * rows when joined with `AND`. When the filter is disabled (dev env
 * with ALLOW_SEED_DATA=1) returns `undefined` so callers can spread it
 * conditionally.
 */
export function notSeedRequestWhere(): Prisma.RequestWhereInput | undefined {
  if (ALLOW_SEED_DATA) return undefined;

  // Build NOT clauses — Prisma supports `mode: "insensitive"` on the
  // top-level string filter (StringFilter), but not on the nested
  // NestedStringFilter used inside `not: { ... }`. So we instead use
  // `NOT: [{ field: { contains, mode } }, ...]` which negates the
  // whole top-level filter and accepts `mode`.
  const titleContainsClauses = TEST_TITLE_PATTERNS.map((p) => ({
    title: { contains: p, mode: "insensitive" as const },
  }));

  const exactTitleClauses = TEST_TITLE_EXACT.map((t) => ({
    title: { equals: t, mode: "insensitive" as const },
  }));

  const seedEmailClauses = TEST_EMAIL_PATTERNS.map((p) => ({
    user: { email: { contains: p, mode: "insensitive" as const } },
  }));

  return {
    NOT: [...exactTitleClauses, ...titleContainsClauses, ...seedEmailClauses],
  };
}

/**
 * Same idea but applied to a User row (for public specialist lists,
 * thread participant filters, etc.).
 */
export function notSeedUserWhere(): Prisma.UserWhereInput | undefined {
  if (ALLOW_SEED_DATA) return undefined;

  return {
    NOT: TEST_EMAIL_PATTERNS.map((p) => ({
      email: { contains: p, mode: "insensitive" as const },
    })),
  };
}

/**
 * Predicate version for in-memory filtering when a Prisma where is
 * inconvenient (e.g. post-aggregation results).
 */
export function isSeedTitle(title: string | null | undefined): boolean {
  if (!title) return false;
  const lower = title.toLowerCase().trim();
  if (TEST_TITLE_EXACT.includes(lower)) return true;
  return TEST_TITLE_PATTERNS.some((p) => lower.includes(p.toLowerCase()));
}

export function isSeedEmail(email: string | null | undefined): boolean {
  if (!email) return false;
  const lower = email.toLowerCase();
  return TEST_EMAIL_PATTERNS.some((p) => lower.includes(p));
}

export const seedFilterEnabled = !ALLOW_SEED_DATA;
